### ISSUE TITLE
Twitch Plays: allow ' in place of ’ for clock-face coordinates

### ISSUE THREAD

**Issue by stormvsn** [Timwi/KtaneCoordinates#1]
The various clock-face coordinates ("12 o’clock" and so on) are defined using Unicode glyph U+2019, right single quotation mark. This is fine (and probably looks better on the bomb), but when defusing this module on Twitch, it would be nice to be able to use Unicode glyph U+0029, apostrophe, because that's the one on my keyboard.

**Comment by Timwi** [comment]
Fair point. You _can_ just write `12 o` because that’s sufficiently unique, but I’ll add the ability to use the apostrophe. Thanks for pointing this out.
